name: kcds
channels:
  - conda-forge
  - r 
  - nodefaults
dependencies:
  - altair=4.1.0
  - altair_data_server=0.4.1
  - altair_saver=0.5.0
  - altair_viewer=0.3.0
  - black=21.5b2
  - dash-bootstrap-components=0.12.2
  - dash-core-components=1.16.0
  - dash-html-components=1.1.3
  - dash=1.20.0
  - flake8-nb=0.3.0
  - flake8=3.9.2
  - isort=5.9.1
  - jupyter-server-proxy 
  - jupyterlab-git
  - jupyterlab_code_formatter
  - jupytext
  - matplotlib
  - nbgitpuller
  - openpyxl=3.0.7
  - panel
  - pytest
  - python-graphviz=0.16
  - r-base 
  - r-caret 
  - r-cowplot 
  - r-crayon 
  - r-devtools 
  - r-e1071 
  - r-forecast 
  - r-ggally 
  - r-gridextra 
  - r-hexbin 
  - r-htmltools 
  - r-htmlwidgets 
  - r-infer 
  - r-irkernel 
  - r-islr
  - r-kknn 
  - r-nycflights13 
  - r-palmerpenguins
  - r-randomforest 
  - r-rcurl 
  - r-rmarkdown 
  - r-rodbc 
  - r-rpostgres 
  - r-rsqlite 
  - r-shiny 
  - r-testthat 
  - r-tidymodels 
  - r-tidyverse 
  - scikit-learn
  - unixodbc
  - vega_datasets=0.9.0
  - xgboost
  - xlrd=2.0.1
